#!/bin/sh
#
# @name Generic HexaOcta X geometry
#
# @type HexaOcta x
# @class Copter
#
# @maintainer x Hoppz <hoppz520@163.com>
#
# @board pixhawk-v6x
#

. ${R}etc/init.d/rc.mc_defaults

# param set-default NAV_ACC_RAD 2

# param set-default RTL_DESCEND_ALT 10
# param set-default RTL_RETURN_ALT 30

param set-default CA_ROTOR_COUNT 16
# Bottom motors

# Rotor 1
# param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR0_PX 0.46
param set-default CA_ROTOR0_PY 0.19
param set-default CA_ROTOR0_PZ -0.04
# Rotor 2
# param set-default CA_ROTOR1_KM -0.05
param set-default CA_ROTOR1_PX -0.46
param set-default CA_ROTOR1_PY -0.19
param set-default CA_ROTOR1_PZ -0.04
# Rotor 3
param set-default CA_ROTOR2_PX 0.19
param set-default CA_ROTOR2_PY 0.46
param set-default CA_ROTOR2_PZ -0.04

# Rotor 4
param set-default CA_ROTOR3_PX -0.46
param set-default CA_ROTOR3_PY 0.19
param set-default CA_ROTOR3_PZ -0.04

# Rotor 5
param set-default CA_ROTOR4_PX 0.46
param set-default CA_ROTOR4_PY -0.19
param set-default CA_ROTOR4_PZ -0.04

# Rotor 6
param set-default CA_ROTOR5_PX -0.19
param set-default CA_ROTOR5_PY -0.46
param set-default CA_ROTOR5_PZ -0.04

# Rotor 7
# param set-default CA_ROTOR6_KM -0.05
param set-default CA_ROTOR6_PX 0.19
param set-default CA_ROTOR6_PY -0.46
param set-default CA_ROTOR6_PZ -0.04
# Rotor 8
# param set-default CA_ROTOR7_KM -0.05
param set-default CA_ROTOR7_PX -0.19
param set-default CA_ROTOR7_PY 0.46
param set-default CA_ROTOR7_PZ -0.04

#Top motors
# Rotor 9
param set-default CA_ROTOR8_PX 0.46
param set-default CA_ROTOR8_PY 0.19
param set-default CA_ROTOR8_PZ 0.04

# Rotor 10
param set-default CA_ROTOR9_PX -0.46
param set-default CA_ROTOR9_PY -0.19
param set-default CA_ROTOR9_PZ  0.04

# Rotor 11
# param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR10_PX 0.19
param set-default CA_ROTOR10_PY 0.46
param set-default CA_ROTOR10_PZ 0.04

# Rotor 12
# param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR11_PX -0.46
param set-default CA_ROTOR11_PY 0.19
param set-default CA_ROTOR11_PZ 0.04
# Rotor 13
# param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR12_PX 0.46
param set-default CA_ROTOR12_PY -0.19
param set-default CA_ROTOR12_PZ 0.04

# Rotor 14
# param set-default CA_ROTOR0_KM -0.05
param set-default CA_ROTOR13_PX -0.19
param set-default CA_ROTOR13_PY -0.46
param set-default CA_ROTOR13_PZ 0.04

# Rotor 15
param set-default CA_ROTOR14_PX 0.19
param set-default CA_ROTOR14_PY -0.46
param set-default CA_ROTOR14_PZ 0.04

# Rotor 16
param set-default CA_ROTOR15_PX -0.19
param set-default CA_ROTOR15_PY 0.46
param set-default CA_ROTOR15_PZ 0.04
